[[runtimes]]
name = "cpython3.13"
python_implementation = "cpython@3.13.11"
requirements = []
platforms = [
    "linux_x86_64",
]


[[applications]]
name = "server"
launch_module = "../../main.py"
runtime = "cpython3.13"
requirements = [
    "fastapi==0.140.0",
    "uvicorn==0.38.0",
    "openresponses-types==2.4.0",
    "httpx==0.28.1",
    ]

[tool.uv]
environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]
exclude-newer = "2026-07-28T19:44:30+05:30"

[tool.uv.exclude-newer-package]
openresponses-types = "2026-08-06T00:00:00Z"
